### ISSUE TITLE
Decide how we implement search

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/documentation-platform#20]
### Description
We want a solution that will allow us to search through we will decide to keep the content in. This needs to tie in the overall docs framework and folder structure we decide to go with in #6.

See discussion in Slack for suggestions. 

### Requirements

- [ ] Ability to index/search in files locally in the repository. Regardless of folder structure.
- [ ] A reasonable search algorithm. One occurrence of a term in header should probably rank higher than a the same occurrence in the page body. 
- [ ] No need for page tagging or any other manual work. 
- [ ] Controllable external dependencies. 
- [ ] Full control over the way the search looks.

**Comment by sobolev-alexey** [comment]
I compared 2 search solutions: `Lunr.js` and `Algolia`.

The main difference between these two is that `Lunr.js` runs on client and indexes all documents in real time. It is also possible to pre-build index on server and deliver it to the client.
This library is open source, widely user and has strong community support.
One major disadvantage of the library is that its search results a full documents/pages, where the keyword was found. It doesn't point you to the keyword or specific paragraph out of the box.

It supports search as you type, also it supports complex search patterns like `+foo bar -baz` (searches for documents that must contain “foo”, might contain “bar” and must not contain “baz”).

`Algolia` is a *Search-as-a-Service*, where you need to be registered customer, sign up for a subscription plan (a free of charge *"open source"* plan is available), and will get a monthly quote of searches. Once this quote is reached, no search results are returned.
Algolia internally operates with a sort of NoSQL database, it accepts files in JSON format and has extensive search algorithms. 
It also has a crawler, that can crawl an existing site, parse it content and build search index on top of it. One major limitation on this is that the site should be live and have a finalized content in order to be crawled and indexed.
```
Your website must have some final content. We won't index empty websites nor those filled with lorem ipsum placeholder content. Please, wait until you have written some documentation before applying. 
```

Given the above limitation, I'd suggest to use `Lunr.js` for now until the site is under development. Once we have a final content, we can very easy add Algolia search, which provides more user friendly interface and can go directly to the searched keyword in the document.

**Comment by sobolev-alexey** [comment]
A good example on how to add `Lunr.js` search can be found here https://github.com/mrvautin/githubdocs

**Comment by jakubcech** [comment]
I don't find the inability to go to the searched keyword in a document to be that big a downside. I think it's useful for reference documentation, for example. Not that important for conceptual documentation where you you usually search for whole concepts, which are then covered by the page as is - the user would read the whole page or a part of the page, not just skim through a very specific part of an API call, for example. But I might be wrong in perceiving how docuemntation is used by different personas, Andrew/Nelson might have a better idea. 

I'd go with Lunr.js based on you found, good stuff!
